name: ako-cluster-role
allow_unlabelled_access: false
filters:
- enabled: true
  match_label:
    key: clustername
    values:
    - <k8-cluster-name place holder>
  match_operation: ROLE_FILTER_EQUALS
privileges:
- resource: PERMISSION_VIRTUALSERVICE
  type: WRITE_ACCESS
- resource: PERMISSION_POOL
  type: WRITE_ACCESS
- resource: PERMISSION_POOLGROUP
  type: WRITE_ACCESS
- resource: PERMISSION_HTTPPOLICYSET
  type: WRITE_ACCESS
- resource: PERMISSION_NETWORKSECURITYPOLICY
  type: READ_ACCESS
- resource: PERMISSION_DNSPOLICY
  type: READ_ACCESS
- resource: PERMISSION_NETWORKPROFILE
  type: READ_ACCESS
- resource: PERMISSION_APPLICATIONPROFILE
  type: READ_ACCESS
- resource: PERMISSION_APPLICATIONPERSISTENCEPROFILE
  type: READ_ACCESS
- resource: PERMISSION_HEALTHMONITOR
  type: READ_ACCESS
- resource: PERMISSION_ANALYTICSPROFILE
  type: READ_ACCESS
- resource: PERMISSION_IPAMDNSPROVIDERPROFILE
  type: READ_ACCESS
- resource: PERMISSION_CUSTOMIPAMDNSPROFILE
  type: READ_ACCESS
- resource: PERMISSION_TRAFFICCLONEPROFILE
  type: READ_ACCESS
- resource: PERMISSION_ICAP
  type: READ_ACCESS
- resource: PERMISSION_IPADDRGROUP
  type: READ_ACCESS
- resource: PERMISSION_STRINGGROUP
  type: READ_ACCESS
- resource: PERMISSION_VSDATASCRIPTSET
  type: WRITE_ACCESS
- resource: PERMISSION_PROTOCOLPARSER
  type: READ_ACCESS
- resource: PERMISSION_SSLPROFILE
  type: READ_ACCESS
- resource: PERMISSION_AUTHPROFILE
  type: READ_ACCESS
- resource: PERMISSION_PINGACCESSAGENT
  type: READ_ACCESS
- resource: PERMISSION_PKIPROFILE
  type: WRITE_ACCESS
- resource: PERMISSION_SSLKEYANDCERTIFICATE
  type: WRITE_ACCESS
- resource: PERMISSION_CERTIFICATEMANAGEMENTPROFILE
  type: READ_ACCESS
- resource: PERMISSION_HARDWARESECURITYMODULEGROUP
  type: READ_ACCESS
- resource: PERMISSION_SSOPOLICY
  type: READ_ACCESS
- resource: PERMISSION_WAFPROFILE
  type: READ_ACCESS
- resource: PERMISSION_WAFPOLICY
  type: READ_ACCESS
- resource: PERMISSION_ERRORPAGEPROFILE
  type: READ_ACCESS
- resource: PERMISSION_CLOUD
  type: WRITE_ACCESS
- resource: PERMISSION_SERVICEENGINEGROUP
  type: WRITE_ACCESS
- resource: PERMISSION_NETWORK
  type: READ_ACCESS
- resource: PERMISSION_VRFCONTEXT
  type: WRITE_ACCESS
- resource: PERMISSION_L4POLICYSET
  type: WRITE_ACCESS
- resource: PERMISSION_TENANT
  type: READ_ACCESS
- resource: PERMISSION_USER
  type: READ_ACCESS
- resource: PERMISSION_ROLE
  type: WRITE_ACCESS
- resource: PERMISSION_CONTROLLER
  type: WRITE_ACCESS
tenant_ref: https://localhost/api/tenant/admin#admin
